name: rewise_neet
description: "A Rewise Tech NEET AI Tutor app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  multiple_result: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  build_runner: ^2.4.6
  json_serializable: ^6.10.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  generate: true
